apiVersion: v1
kind: Service
metadata:
  name: organization
  namespace: default
  labels:
    app: organization
spec:
  selector:
    app: organization
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
